# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51eab6a3864fa28a362be54973e3a1b8229e8fedfbb5f0d458688059ca161cab7ceaf8bd117572959e0857f86917d2f3690ac030947c217e5b4574fe2ea93418

test:
  secret_key_base: bae8328e27b66c3ccb9734d4fd96cfda398c4d3b5b6db1b4e9b14b4b2abfb7fd6889d539866ca07f51710a15fd0eb7127dac7944d3af61a5ebff34479db51e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
